CREATE DATABASE QuanLyHocVien
USE QuanLyHocVien
CREATE TABLE HOCVIEN
(
	MaHocVien INT,
	HoTen NVARCHAR(255) NOT NULL,
	NgaySinh DATE NOT NULL,
	GioiTinh BIT,
	SoDienThoai VARCHAR(255),
	DiaChi NVARCHAR(255),
	TinhTrang BIT DEFAULT 1,
	CONSTRAINT pk_HOCVIEN PRIMARY KEY(MaHocVien)
)

CREATE TABLE KHOAHOC
(
	MaKhoaHoc INT,
	TenKhoaHoc NVARCHAR(255),
	MoTa NVARCHAR(255),
	NgayBatDau DATE,
	NgayKetThuc DATE,
	TinhTrang BIT DEFAULT 1,
	CONSTRAINT pk_KHOAHOC PRIMARY KEY(MaKhoaHoc)
)

CREATE TABLE LOPHOC
(
	MaLopHoc INT,
	MaKhoaHoc INT,
	MaHocVien INT,
	NgayDangKy DATE,
	TinhTrang BIT DEFAULT 1,
	CONSTRAINT pk_LOPHOC PRIMARY KEY(MaLopHoc,MaKhoaHoc,MaHocVien),
	CONSTRAINT fk1_LOPHOC FOREIGN KEY(MaKhoaHoc) REFERENCES dbo.KHOAHOC(MaKhoaHoc),
	CONSTRAINT fk2_LOPHOC FOREIGN KEY(MaHocVien) REFERENCES dbo.HOCVIEN(MaHocVien)
)

CREATE TABLE TAIKHOAN
(
	TenDangNhap VARCHAR(50) NOT NULL PRIMARY KEY,
	MatKhau VARCHAR(50),
	TinhTrang BIT
)

SELECT* FROM dbo.HOCVIEN
SELECT* FROM dbo.KHOAHOC
SELECT* FROM dbo.LOPHOC
GO

ALTER TABLE dbo.LOPHOC
NOCHECK CONSTRAINT ALL
ALTER TABLE dbo.KHOAHOC
NOCHECK CONSTRAINT ALL
ALTER TABLE dbo.HOCVIEN
NOCHECK CONSTRAINT ALL
GO

CREATE TRIGGER tg_HocVien ON dbo.HOCVIEN
FOR DELETE AS
BEGIN
	DELETE dbo.LOPHOC
	FROM dbo.LOPHOC JOIN Deleted ON Deleted.MaHocVien = LOPHOC.MaHocVien
END
GO

CREATE TRIGGER tg_KhoaHoc ON dbo.KHOAHOC
FOR DELETE AS
BEGIN
	DELETE dbo.LOPHOC
	FROM dbo.LOPHOC JOIN Deleted ON Deleted.MaKhoaHoc = LOPHOC.MaKhoaHoc
END
GO


CREATE TRIGGER tg_LopHoc ON dbo.LOPHOC
FOR INSERT AS
BEGIN
	IF NOT EXISTS(SELECT* FROM dbo.HOCVIEN JOIN Inserted ON Inserted.MaHocVien = HOCVIEN.MaHocVien)	ROLLBACK TRAN;
	IF NOT EXISTS(SELECT* FROM dbo.KHOAHOC JOIN Inserted ON Inserted.MaKhoaHoc = KHOAHOC.MaKhoaHoc) ROLLBACK TRAN;
END
GO

SELECT (SELECT COUNT(*) FROM dbo.KHOAHOC) 'SoKhoaHoc', (SELECT COUNT(*) FROM dbo.HOCVIEN) 'SoHocVien', COUNT(MaLopHoc+LOPHOC.MaKhoaHoc) 'SoLopHoc'
FROM dbo.LOPHOC

--SELECT  CAST(MONTH(NgayDangKy) AS VARCHAR(2)) + '-'
--        + CAST(YEAR(NgayDangKy) AS VARCHAR(4)) 'NgayDangKy' ,
--        COUNT(*) AS 'SoLuong'
--FROM    dbo.LOPHOC
--GROUP BY YEAR(NgayDangKy) ,
--        MONTH(NgayDangKy)
--ORDER BY MONTH(NgayDangKy)
